"""fix timestamp 2

Revision ID: c6f2fc18b6a4
Revises: b96ad96f7249
Create Date: 2025-02-19 10:28:52.059624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c6f2fc18b6a4'
down_revision: Union[str, None] = 'b96ad96f7249'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
